apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  # namespace: back-end
spec:
  type: ExternalName
  externalName: cloud2.c3mxoof7sjmu.ap-southeast-1.rds.amazonaws.com # FQDN
  ports:
  - port: 3306
    targetPort: 3306